# Generated by Django 5.0.4 on 2024-05-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('VIP', 'VIP'), ('Pro', 'Pro')], default='Normal', max_length=10),
        ),
    ]
