# Generated by Django 5.0.4 on 2024-05-06 03:15

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_posts_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='images1',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='posts',
            name='images2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='posts',
            name='images3',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='posts',
            name='images4',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='posts',
            name='images5',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='default.jpg', null=True, upload_to=app.models.use_directory_paths)),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('wallet', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Information',
                'verbose_name_plural': 'User Information',
                'ordering': ['date'],
            },
        ),
    ]
