# Generated by Django 5.0.4 on 2024-05-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wallet',
        ),
    ]
