# Generated by Django 5.0.4 on 2024-05-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='image_user',
        ),
    ]
