# Generated by Django 5.0.4 on 2024-05-08 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_image_profile_image_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image_user',
            new_name='image',
        ),
    ]
