# Generated by Django 5.0.4 on 2024-05-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_image_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
