# Generated by Django 5.0.4 on 2024-05-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_posts_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
