# Generated by Django 5.0.4 on 2024-05-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_posts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='images1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='images2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='images3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='images4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='images5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
