# Generated by Django 5.0.4 on 2024-05-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_image_title_posts_images_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='images_title',
            new_name='images',
        ),
    ]
