# Generated by Django 5.0.4 on 2024-05-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_images_title_posts_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='images',
            new_name='images_title',
        ),
    ]
